### PR TITLE
Add the plugin in the recommended config

### PR DESCRIPTION
**Pull request by nklhtv**
Each eslint plugin adds itself to the plugins as part of the recommended config.
@artlaman please review

### CODE REVIEW

**Comment by artlaman** [comment]
I don't quite understand what this line of code does. 😅 Can you share a link to the documentation please?

**Comment by nklhtv** [comment]
@artlaman, There is an example here: https://eslint.org/docs/latest/extend/plugins#configs-in-plugins
If this line is not there i must list the index plugin in the plugins array of my config.
If this line is there i can omit it (in case i extends from the recommeneded config ofc).

**Comment by artlaman** [comment]
Okay, now I understand, thank you very much for the explanation.

**Comment by artlaman** [comment]
@nklhtv Thank you one more time!

**Pull request merged**
